#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "gitingest",
#     "asyncio",
# ]
# ///

"""
Simple Repository Summarizer

Quick script to generate a summary of a Git repository.
Perfect for getting a quick overview of any codebase.

Usage:
    python repo_summary.py <repository-url>
"""

import sys
import re
from typing import Dict, List

try:
    from gitingest import ingest
except ImportError:
    print("Error: gitingest package not installed.")
    print("Install with: pip install gitingest")
    sys.exit(1)


def summarize_repository(repo_url: str) -> str:
    """
    Generate a concise summary of a repository.
    Returns markdown-formatted summary.
    """
    print(f"Fetching repository: {repo_url}")

    # Get repository data
    summary, tree, content = ingest(repo_url)

    # Parse summary info
    repo_info = {}
    for line in summary.split('\n'):
        if ':' in line:
            key, value = line.split(':', 1)
            repo_info[key.strip()] = value.strip()

    # Split into files
    files = split_content(content)

    # Analyze
    stats = analyze_files(files)

    # Generate markdown
    md = f"""# Repository Summary

## Basic Information
- **Repository**: {repo_info.get('Repository', 'Unknown')}
- **Files Analyzed**: {repo_info.get('Files analyzed', 'Unknown')}
- **Estimated Tokens**: {repo_info.get('Estimated tokens', 'Unknown')}

## Overview
{stats['overview']}

## Structure
```
{tree[:500]}...
```

## File Statistics
- **Total Files**: {stats['total_files']}
- **Total Lines**: {stats['total_lines']:,}
- **Languages**: {', '.join(stats['languages'])}

## Top Files by Size
"""

    # Add top files
    for file_info in stats['largest_files'][:10]:
        md += f"- **{file_info['path']}** - {file_info['lines']} lines\n"

    md += "\n## Key Functions\n"
    for func in stats['top_functions'][:15]:
        md += f"- `{func}`\n"

    md += "\n## Key Classes/Types\n"
    for cls in stats['top_classes'][:10]:
        md += f"- `{cls}`\n"

    # Add sections if they exist
    if stats['readme']:
        md += "\n## README\n"
        md += f"```\n{stats['readme'][:500]}...\n```\n"

    if stats['config_files']:
        md += "\n## Configuration Files\n"
        for cfg in stats['config_files']:
            md += f"- {cfg}\n"

    if stats['test_files']:
        md += "\n## Test Files\n"
        for test in stats['test_files'][:10]:
            md += f"- {test}\n"

    md += f"""
---
*Generated by GitIngest Summary Tool*
"""

    return md


def split_content(content: str) -> List[Dict]:
    """Split content into individual files"""
    files = []
    current_file = None

    for line in content.split('\n'):
        if line.startswith('FILE: '):
            if current_file:
                files.append(current_file)
            current_file = {
                'path': line.replace('FILE: ', ''),
                'content': []
            }
        elif current_file:
            current_file['content'].append(line)

    if current_file:
        files.append(current_file)

    return files


def analyze_files(files: List[Dict]) -> Dict:
    """Analyze files and extract statistics"""
    stats = {
        'total_files': len(files),
        'total_lines': 0,
        'languages': set(),
        'largest_files': [],
        'top_functions': [],
        'top_classes': [],
        'readme': '',
        'config_files': [],
        'test_files': [],
        'overview': ''
    }

    for file in files:
        path = file['path']
        content = '\n'.join(file['content'])
        line_count = len(file['content'])

        stats['total_lines'] += line_count
        stats['largest_files'].append({
            'path': path,
            'lines': line_count
        })

        # Detect language
        ext = path.split('.')[-1] if '.' in path else ''
        lang_map = {
            'py': 'Python',
            'js': 'JavaScript',
            'ts': 'TypeScript',
            'java': 'Java',
            'cpp': 'C++',
            'c': 'C',
            'cs': 'C#',
            'go': 'Go',
            'rs': 'Rust',
            'php': 'PHP'
        }
        if ext in lang_map:
            stats['languages'].add(lang_map[ext])

        # Special files
        if 'readme' in path.lower():
            stats['readme'] = content[:1000]

        if path.endswith(('.json', '.yaml', '.yml', '.toml', '.ini', '.cfg')):
            stats['config_files'].append(path)

        if 'test' in path.lower():
            stats['test_files'].append(path)

        # Extract functions
        for line in file['content']:
            # Python
            match = re.match(r'\s*def\s+(\w+)', line)
            if match:
                stats['top_functions'].append(match.group(1))

            # JavaScript
            match = re.match(r'\s*function\s+(\w+)', line)
            if match:
                stats['top_functions'].append(match.group(1))

            # Classes
            match = re.match(r'\s*class\s+(\w+)', line)
            if match:
                stats['top_classes'].append(match.group(1))

    # Sort largest files
    stats['largest_files'].sort(key=lambda x: x['lines'], reverse=True)

    # Remove duplicates
    stats['top_functions'] = list(dict.fromkeys(stats['top_functions']))
    stats['top_classes'] = list(dict.fromkeys(stats['top_classes']))

    # Generate overview
    stats['overview'] = generate_overview(stats)

    return stats


def generate_overview(stats: Dict) -> str:
    """Generate a brief overview text"""
    lang_count = len(stats['languages'])
    lang_str = ', '.join(sorted(stats['languages'])) if stats['languages'] else 'Unknown'

    overview = f"""This repository contains **{stats['total_files']} files** with **{stats['total_lines']:,} lines of code**.
Primary languages: **{lang_str}**."""

    if stats['config_files']:
        overview += f"\n\nIncludes configuration files, suggesting it's a complete project setup."

    if stats['test_files']:
        test_ratio = len(stats['test_files']) / stats['total_files'] * 100
        overview += f"\n\nHas {len(stats['test_files'])} test files ({test_ratio:.1f}% of total)."

    return overview


def main():
    if len(sys.argv) < 2:
        print("Usage: python repo_summary.py <repository-url>")
        print("\nExample:")
        print("  python repo_summary.py https://github.com/octocat/Hello-World")
        sys.exit(1)

    repo_url = sys.argv[1]

    try:
        summary = summarize_repository(repo_url)

        # Print to stdout
        print(summary)

        # Also save to file
        output_file = "repository-summary.md"
        with open(output_file, 'w') as f:
            f.write(summary)

        print(f"\n Summary saved to {output_file}")

    except Exception as e:
        print(f"\n Error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
